# 256 colors support (requires `TERM=xterm-256color` outside of tmux)
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

# Enable hyperlinks
set -ag terminal-features "*:hyperlinks"

# Unbind the prefix and bind it to Ctrl-q
unbind C-b
set -g prefix C-q
bind C-q send-prefix

# Enable mouse and clipboard
set -g mouse on
set -sg set-clipboard on

# VIM mode
set -wg mode-keys vi

# Reduce ESC delay
set -sg escape-time 10

# Neovim needs it
set -g focus-events on

# Vi-like panes movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Theming
# #51c4d3 pubulan as bright cyan
# #1e9eb3 cuilan as cyan
# #101f30 anlan as black
# #5e616d yuweihui as grey
# #e4dfd7 zhenzhuhui as fg
set -g status on
set -g status-bg "#101f30"
set -g status-fg "#e4dfd7"
set -g status-justify "left"

set -g status-left "#[bg=#1e9eb3,fg=#101f30,bold] #S #[bg=#101f30,fg=#e4dfd7,nobold,noitalics,nounderscore] "
set -g status-left-style none
set -g status-right ""
set -g status-right-style none
set -g status-right-length 0

set -g window-status-current-style "bg=#101f30,fg=#51c4d3"
set -g window-status-current-format " #I:#W#{?window_zoomed_flag,*Z,} "
set -g window-status-style "bg=#101f30,fg=#5e616d"
set -g window-status-format " #I:#W#{?window_zoomed_flag,*Z,} "
set -g window-status-separator ""
