[settings]
default_target_type = "symbolic"

[vim.files]
"vim/.vimrc" = "~/.vimrc"
"vim/.vim/colors/lettepa.vim" = "~/.vim/colors/lettepa.vim"

[zellij.files]
zellij = "~/.config/zellij"

[tmux-remote.files]
"tmux/remote.tmux.conf" = "~/.tmux.conf"

[tmux-local.files]
"tmux/local.tmux.conf" = "~/.tmux.conf"
